### ISSUE TITLE
Unhandled exception while opening the "Поиск стыков" form.

### ISSUE THREAD

**Issue by IgorVskpsn** [olga-jane/prizm#1077]
Steps to get the error message:
1. Start the program.
2. Go to "Входной контроль и строительство" -> "Поиск стыков"

Expected result: The error shows up:
 Unhandled exception has occurred ...
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Prizm.Main.Common.EnumWrapper`1[Prizm.Domain.Entity.Construction.JointStatus]'.
   at Prizm.Main.Forms.Joint.Search.JointSearchXtraForm.RefreshCombo()
   at Prizm.Main.Forms.Joint.Search.JointSearchXtraForm.JointSearchXtraForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at Prizm.Main.Forms.MainChildForm.PrizmForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

by: Igor Vysokopoyasniy

**Comment by olga-jane** [comment]
seems to be fixed here "refresh searchJoint in according to localized Combobox and CheckedCombo #1066"
