### ISSUE TITLE
Error arrived during saving changes to the table on the "Входной контроль" form.

### ISSUE THREAD

**Issue by IgorVskpsn** [olga-jane/prizm#1082]
Problem may be hard to repeat.

Steps to get the error:
1. Start the program.
2. Go to "Настройки" -> "Комплектующие"
3. Add a new product type to the list (in tested case it had 2 connectors).
4. Go to "Входной контроль и строительство" -> "Новое комплектующее"
5. Create a new product of previously created type.
6. Go to "Входной контроль и строительство" -> "Входной контроль" 
7. Press the "Найти и редактировать для контроля" button and choose your product.
8. Fill add some records to the table below.
9. Click save button.

Expected result: The error arrives

NHibernate.LazyInitializationException: Initializing[Unavailable#]-failed to lazily initialize a collection, no session or session was closed
   at NHibernate.Collection.AbstractPersistentCollection.ThrowLazyInitializationException(String message)
   at NHibernate.Collection.AbstractPersistentCollection.ThrowLazyInitializationExceptionIfNotConnected()
   at NHibernate.Collection.AbstractPersistentCollection.Initialize(Boolean writing)
   at NHibernate.Collection.AbstractPersistentCollection.Read()
   at NHibernate.Collection.PersistentBag.ToString()
   at Prizm.Data.DAL.Hibernate.AuditInterceptor.OnFlushDirty(Object entity, Object id, Object[] currentState, Object[] previousState, String[] propertyNames, IType[] types)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.InvokeInterceptor(ISessionImplementor session, Object entity, EntityEntry entry, Object[] values, IEntityPersister persister)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.HandleInterception(FlushEntityEvent event)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.ScheduleUpdate(FlushEntityEvent event)
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.OnFlushEntity(FlushEntityEvent event)
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEntities(FlushEvent event)
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEverythingToExecutions(FlushEvent event)
   at NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event)
   at NHibernate.Impl.SessionImpl.Flush()
   at NHibernate.Transaction.AdoTransaction.Commit()
   at Prizm.Data.DAL.Hibernate.AbstractHibernateRepository`2.Commit()
   at Prizm.Main.Forms.Parts.Inspection.SaveInspectionTestResultsCommand.Execute()
   at Prizm.Main.Commands.CommandInfo.SimpleButtonAttacher.btn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

How it looks:
![screen1](https://cloud.githubusercontent.com/assets/10723795/5921431/97a58a50-a64c-11e4-8c39-7bc644fbf91d.jpg)
![screen2](https://cloud.githubusercontent.com/assets/10723795/5921432/97a5e93c-a64c-11e4-994b-b1181bb59422.jpg)
![screen3](https://cloud.githubusercontent.com/assets/10723795/5921430/97a39100-a64c-11e4-95ba-94db123090b9.jpg)
![screen4](https://cloud.githubusercontent.com/assets/10723795/5921433/97a75506-a64c-11e4-8f8b-7fb7b19a5090.jpg)

by: Igor Vysokopoyasniy

**Comment by DmitrySidorov** [comment]
the crush do not reproduced in this scenario, needed additional investigation

**Comment by AleksMorozova** [comment]
fixed - settings, MillInspectionXtraForm #1305
