### ISSUE TITLE
It is impossible to create a New Component

### ISSUE THREAD

**Issue by DmitrySidorov** [olga-jane/prizm#1241]
Scenario (at constraction):
1.Open "new component"
2.Fill all requared fields
3.Save component

Result:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Prizm.Main.Forms.Component.NewEdit.SaveComponentCommand.Execute()
   at Prizm.Main.Commands.CommandInfo.SimpleButtonAttacher.btn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by olga-jane** [comment]
serg7: при создании viewModel.Component.Id null

**Comment by olga-jane** [comment]
could have been caused by "Saving files should be one transaction with saving the entity #854"
