### ISSUE TITLE
Exception while adding second attachment

### ISSUE THREAD

**Issue by kapcia** [olga-jane/prizm#1290]
STR:
On construction create component
Save it
Add first  attachment and click save
Add second attachment and save
Result: exception
************* Exception Text **************
NHibernate.TransactionException: Transaction not successfully started
   at NHibernate.Transaction.AdoTransaction.CheckBegun()
   at NHibernate.Transaction.AdoTransaction.Commit()
   at Prizm.Main.Forms.Component.ComponentRepositories.Commit()
   at Prizm.Main.Forms.Component.NewEdit.SaveComponentCommand.Execute()
   at Prizm.Main.Commands.CommandInfo.SimpleButtonAttacher.btn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![capture1](https://cloud.githubusercontent.com/assets/7581458/6083509/bc081cea-ae31-11e4-84ae-0d4963ec82a7.PNG)

**Comment by olga-jane** [comment]
seems to be broken by "Saving files should be one transaction with saving the entity #854"
