### ISSUE TITLE
Date conversion crash at SaveSettings when create new sizetype

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1334]
![image](https://cloud.githubusercontent.com/assets/8179067/6147006/898f1b9c-b1fb-11e4-96e4-3702b6d6ae8d.png)

1) go to settings
2) create new size type and fill data as shown on screen.
3) press save.

Crash details:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at Prizm.Main.Common.DateExtension.IsValid(Nullable`1 date)
   at Prizm.Main.Forms.Settings.SaveSettingsCommand.<DateCheck>b__5(User x)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Prizm.Main.Forms.Settings.SaveSettingsCommand.DateCheck()
   at Prizm.Main.Forms.Settings.SaveSettingsCommand.Execute()
   at Prizm.Main.Commands.CommandInfo.SimpleButtonAttacher.btn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by olga-jane** [comment]
Crash on settings #1329
