### ISSUE TITLE
Find deactivated pipe [Mill] v 1.0.32.9991

### ISSUE THREAD

**Issue by AlexeyMityaev** [olga-jane/prizm#1509]
1. Open "Mill"
2. Select "New pipe"
3. Save new pipe, do not close this tab
4. Open "Mill"
5. Select "Find pipe"
6. Make sure you found recently created pipe
7. Click on the tab of your new pipe
8. Click on checkbox "Pipe is deactivated" and choose "Yes"
9. Click on the tab "Search pipe"
10. Double click on row with your new pipe

![image](https://cloud.githubusercontent.com/assets/11043520/6264260/f0bfbf26-b82a-11e4-9394-b5fb0e9ed26a.png)

![image](https://cloud.githubusercontent.com/assets/11043520/6264234/913ded70-b82a-11e4-8ffd-b6edb5c00096.png)

************** Exception Text **************
NHibernate.HibernateException: More than one row with the given identifier was found: 9d14c44a-eacd-4f51-a72a-3284684bd6dc, for class: Prizm.Domain.Entity.Mill.Plate
   at NHibernate.Loader.Entity.AbstractEntityLoader.Load(ISessionImplementor session, Object id, Object optionalObject, Object optionalId)
   at NHibernate.Loader.Entity.AbstractEntityLoader.Load(Object id, Object optionalObject, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Load(Object id, Object optionalObject, LockMode lockMode, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultLoadEventListener.LoadFromDatasource(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.DoLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.Load(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.ImmediateLoad(String entityName, Object id)
   at NHibernate.Proxy.AbstractLazyInitializer.Initialize()
   at NHibernate.Proxy.DefaultLazyInitializer.Intercept(InvocationInfo info)
   at PlateProxy.get_Heat()
   at Prizm.Main.Forms.PipeMill.NewEdit.SavePipeCommand.CanExecute()
   at Prizm.Main.Forms.PipeMill.NewEdit.NewSavePipeCommand.CanExecute()
   at Prizm.Main.Commands.CommandInfo.SimpleButtonAttacher.RefreshState()
   at Prizm.Main.Commands.CommandManager.RefreshVisualState()
   at Prizm.Main.Forms.PipeMill.NewEdit.MillPipeNewEditXtraForm.BindCommands()
   at Prizm.Main.Forms.PipeMill.NewEdit.MillPipeNewEditXtraForm.MillPipeNewEditXtraForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at Prizm.Main.Forms.MainChildForm.PrizmForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by AlexeyMityaev** [comment]
Also, after trying to restart program after this error I got new one

![image](https://cloud.githubusercontent.com/assets/11043520/6264345/d7711f0a-b82b-11e4-98bf-70bc09e1ebfb.png)

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Prizm.Main.Forms.Notifications.Data.DublicateNumberLoader.GetOwnerName(Object[] tuple)
   at Prizm.Main.Forms.Notifications.Data.DataNotificationLoader.TransformTuple(Object[] tuple, String[] aliases)
   at NHibernate.Loader.Custom.CustomLoader.GetResultList(IList results, IResultTransformer resultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
   at NHibernate.Impl.SessionImpl.ListCustomQuery(ICustomQuery customQuery, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.SessionImpl.List(NativeSQLQuerySpecification spec, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.SessionImpl.List[T](NativeSQLQuerySpecification spec, QueryParameters queryParameters)
   at NHibernate.Impl.SqlQueryImpl.List[T]()
   at Prizm.Main.Forms.Notifications.Data.DataNotificationLoader.LoadNotificationFromDB()
   at Prizm.Main.Forms.Notifications.NotificationManager.LoadNotificationFromDB()
   at Prizm.Main.Forms.Notifications.NotificationService.RequestAllNotification()
   at Prizm.Main.Forms.MainChildForm.PrizmApplicationXtraForm.PrizmApplicationXtraForm_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at Prizm.Main.Forms.MainChildForm.PrizmForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
