### ISSUE TITLE
crash on pipe (double click on first inspection operation)

### ISSUE THREAD

**Issue by demmy** [olga-jane/prizm#1523]
Steps:
1. make new pipe & set control operations to done
2. press save&new
3. create second pipe
4. double click on first control operation

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Prizm.Main.Controls.InspectorSelectionControl.inspectorsGridView_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   at DevExpress.XtraGrid.Views.Base.ColumnView.RaiseSelectionChanged(SelectionChangedEventArgs e)
   at DevExpress.XtraGrid.Views.Base.ColumnView.OnDataController_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   at DevExpress.Data.DataController.RaiseSelectionChanged(SelectionChangedEventArgs e)
   at DevExpress.Data.Selection.SelectionController.OnSelectionChanged(SelectionChangedEventArgs e)
   at DevExpress.Data.Selection.SelectionController.EndSelection()
   at DevExpress.XtraGrid.Views.Base.BaseView.EndSelection()
   at DevExpress.XtraGrid.Views.Base.ColumnView.SelectFocusedRowCore()
   at DevExpress.XtraGrid.Views.Grid.GridView.SelectFocusedRowCore()
   at DevExpress.XtraGrid.Views.Base.ColumnView.DoAfterMoveFocusedRow(KeyEventArgs e, Int32 prevFocusedHandle, GridColumn prevFocusedColumn, BaseHitInfo hitInfo, Boolean allowCells)
   at DevExpress.XtraGrid.Views.Grid.GridView.DoAfterMoveFocusedRow(KeyEventArgs e, Int32 prevFocusedHandle, GridColumn prevFocusedColumn, BaseHitInfo hitInfo, Boolean allowCells)
   at DevExpress.XtraGrid.Views.Grid.GridView.DoMoveFocusedRow(Int32 delta, KeyEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridRegularRowNavigator.DoNavigation(KeyEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridRegularRowNavigator.OnKeyDown(KeyEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnKeyDown(KeyEventArgs e)
   at DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.Views.Base.Handler.BaseViewHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.GridControl.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by kapcia** [comment]
Client script ecxeption
