### ISSUE TITLE
Something break v1.0.32.9992 only after update v1.0.32.9991 to v1.0.32.9992

### ISSUE THREAD

**Issue by KnightDanila** [olga-jane/prizm#1531]
- [x] PART 1

1. Start Prism-ProBuild
2. Miscellaneous -> audit
![image](https://cloud.githubusercontent.com/assets/11027679/6284002/1ea9bae2-b905-11e4-80d1-c0d689d6a02f.png)

(Does not working after update)
This problem was solved after full reinstallation

Error Details
*****************************************************************************************************************************
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
NHibernate.Exceptions.GenericADOException: could not execute query
[ SELECT this_.userName as y0_ FROM [AuditLog] this_ ]
[SQL: SELECT this_.userName as y0_ FROM [AuditLog] this_] ---> System.Data.SqlClient.SqlException: Invalid column name 'userName'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters)
 

Egoshkin Danila

**Comment by Chifuyu** [comment]
Завод

При создании нового наряда на заказ  вылетает исключение
![yyy3](https://cloud.githubusercontent.com/assets/10714201/6284476/ff568d3e-b8f8-11e4-9844-f39a370f4a9e.png)

при создании трубы вылетает исключение при попытке прохода контроля
![yyy1](https://cloud.githubusercontent.com/assets/10714201/6284497/37570376-b8f9-11e4-9306-a74f51a9c40e.png)

**Comment by Chifuyu** [comment]
Попытка изменения даты сертификата

![yyy1](https://cloud.githubusercontent.com/assets/10714201/6284530/9fdbd174-b8f9-11e4-9fb6-8e0a54c24c40.png)


![yyy1](https://cloud.githubusercontent.com/assets/10714201/6284537/b4a3e18c-b8f9-11e4-9305-4b8ccc004b41.png)

![yyy3](https://cloud.githubusercontent.com/assets/10714201/6284548/ceb10d3e-b8f9-11e4-9d9b-0f1f9ae6ee4b.png)

![yyy1](https://cloud.githubusercontent.com/assets/10714201/6284530/9fdbd174-b8f9-11e4-9fb6-8e0a54c24c40.png)

**Comment by Chifuyu** [comment]
Новая плавка не сохраняется

Завод
Новая труба
Новая плавка
Сохраняем
И она не сохраняется

![ee1](https://cloud.githubusercontent.com/assets/10714201/6284625/d7b0d63e-b8fa-11e4-8def-609ea4776e5e.png)

![ee2](https://cloud.githubusercontent.com/assets/10714201/6284635/eae19cc0-b8fa-11e4-9fcb-cf5f3ca707d1.png)

Хоменко

**Comment by olga-jane** [comment]
previous comments are related - they happened only after update

**Comment by DmitrySidorov** [comment]
PART 1 - do not reproduce
PART 2 - do not reproduce
PART 3 - do not reproduce
PART 4 - do not reproduce

Requires a more detailed scenario and additional information. Does the crush is repeated in the new version of DB (at 23.02.2015)?

**Comment by Chifuyu** [comment]
в новой версии данных ошибок не возникает. есть другая #1576

**Comment by DmitrySidorov** [comment]
Not actual. See issue #1576
