### ISSUE TITLE
Inspection operations for pipe [Mill] v 1.0.33.9990

### ISSUE THREAD

**Issue by AlexeyMityaev** [olga-jane/prizm#1585]
1. Create new pipe or open old one
2. Click on "Inspection operations"
3. Click on "Add" or "Edit" buttons
Note: this error appeared only after updating existing project from v 1.0.32.999 to v 1.0.33.9990

![image](https://cloud.githubusercontent.com/assets/11043520/6325974/8f2541c2-bb55-11e4-9eaf-6ef757129e4b.png)

************** Exception Text **************
Prizm.Data.DAL.RepositoryException: GetAll ---> NHibernate.Exceptions.GenericADOException: could not execute query
[ SELECT this_.id as id1_0_, this_.isActive as isActive1_0_, this_.[language] as column1_3_0_, this_.[text] as column2_3_0_, this_.[idDefect] as column3_3_0_ FROM [CannedMessage] this_ ]
[SQL: SELECT this_.id as id1_0_, this_.isActive as isActive1_0_, this_.[language] as column1_3_0_, this_.[text] as column2_3_0_, this_.[idDefect] as column3_3_0_ FROM [CannedMessage] this_] ---> System.Data.SqlClient.SqlException: Invalid object name 'CannedMessage'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters)
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at Prizm.Data.DAL.Hibernate.AbstractHibernateRepository`2.GetAll()
   --- End of inner exception stack trace ---
   at Prizm.Data.DAL.Hibernate.AbstractHibernateRepository`2.GetAll()
   at Prizm.Main.Forms.PipeMill.NewEdit.Inspections.InspectionAddEditViewModel..ctor(IList`1 tests, IList`1 inspectors, PipeTestResult current, IList`1 statuses)
   at Prizm.Main.Forms.PipeMill.NewEdit.InspectionAddEditXtraForm.GetInspectionViewModel(IList`1 tests, IList`1 inspectors, PipeTestResult current, IList`1 statuses)
   at Prizm.Main.Forms.PipeMill.NewEdit.InspectionAddEditXtraForm.SetupForm(IList`1 tests, IList`1 inspectors, PipeTestResult current, IList`1 statuses)
   at Prizm.Main.Forms.PipeMill.NewEdit.InspectionAddEditXtraForm..ctor(IList`1 tests, IList`1 inspectors, PipeTestResult current, IList`1 statuses)
   at Prizm.Main.Forms.PipeMill.NewEdit.MillPipeNewEditXtraForm.GetInspectionForm(BindingList`1 tests, IList`1 inspectors, PipeTestResult row, IList`1 statuses)
   at Prizm.Main.Forms.PipeMill.NewEdit.MillPipeNewEditXtraForm.EditInspections(BindingList`1 tests, PipeTestResult row, IList`1 insp, BindingList`1 status)
   at Prizm.Main.Forms.PipeMill.NewEdit.MillPipeNewEditXtraForm.inspectionsGridView_DoubleClick(Object sender, EventArgs e)
   at DevExpress.XtraGrid.Views.Base.BaseView.RaiseDoubleClick(EventArgs e)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnDoubleClick(MouseEventArgs ev)
   at DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.Views.Base.Handler.BaseViewHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.GridControl.OnDoubleClick(EventArgs ev)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by AleksMorozova** [comment]
seems not to be reproduced
