### ISSUE TITLE
Replacing external files [Mill] v 1.0.33.9990

### ISSUE THREAD

**Issue by AlexeyMityaev** [olga-jane/prizm#1589]
1. Create new pipe
2. Click on "Attachments" and add new file
3. Save changes
4. Click on "Attachments" again and download this file to the folder with the same file
5. Click "Yes" to replace old file

![image](https://cloud.githubusercontent.com/assets/11043520/6326456/7368745e-bb5a-11e4-8377-dd5f63948111.png)

************** Exception Text **************
System.IO.IOException: The file 'C:\Users\Tester\Desktop\Ex.txt' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Prizm.Main.Forms.ExternalFile.DownloadFileCommand.Execute()
   at Prizm.Main.Forms.ExternalFile.ExternalFilesXtraForm.downloadButton_ButtonClick(Object sender, ButtonPressedEventArgs e)
   at DevExpress.XtraEditors.Repository.RepositoryItemButtonEdit.RaiseButtonClick(ButtonPressedEventArgs e)
   at DevExpress.XtraEditors.ButtonEdit.OnClickButton(EditorButtonObjectInfoArgs buttonInfo)
   at DevExpress.XtraEditors.ButtonEdit.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.TextEdit.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by olga-jane** [comment]
PRISM-24
