### ISSUE TITLE
Exception while opening a form "Новый стык". (Not reproduced yet)

### ISSUE THREAD

**Issue by StaceyN** [olga-jane/prizm#999]
Step to reproduce:
1. Open control and building
2. "Новый стык" 
3. Exception appears.
System.Reflection.TargetInvocationException: Property accessor 'JointConstructionStatus' on object 'Prizm.Main.Forms.Joint.NewEdit.JointNewEditViewModel' threw the following exception:'Object reference not set to an instance of an object.' ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Prizm.Main.Forms.Joint.NewEdit.JointNewEditViewModel.<get_JointConstructionStatus>b__c(JointWeldResult x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Prizm.Main.Forms.Joint.NewEdit.JointNewEditViewModel.get_JointConstructionStatus()
by Necheporenko Anastacia

**Comment by DmitrySidorov** [comment]
This task requires additional investigation. The bug do not reproduce for Mill workstation like a master one.
